export const GET_PRODUCT_LIST_SUCCESS = 'GET_PRODUCT_LIST_SUCCESS';
export const GETTING_PRODUCT_LIST = 'GETTING_PRODUCT_LIST';
export const GETTING_SHOPCART_LIST = 'GETTING_SHOPCART_LIST';
export const GET_SHOPCART_LIST_SUCCESS = 'GET_SHOPCART_LIST_SUCCESS';
export const ADDED_TO_SHOPCART = 'ADDED_TO_SHOPCART';
export const ADDING_TO_SHOPCART = 'ADDING_TO_SHOPCART';
export const UPDATE_AMOUNT_TO_SHOPCART = 'UPDATE_AMOUNT_TO_SHOPCART';
export const DELETE_FROM_SHOPCART = 'DELETE_FROM_SHOPCART';
