export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const GET_ORDER_DETAIL = 'GET_ORDER_DETAIL';
export const ADD_TO_ORDER_LIST = 'ADD_TO_ORDER_LIST';
export const UPDATE_AMOUNT_TO_ORDER_LIST = 'UPDATE_AMOUNT_TO_ORDER_LIST';
export const DELETE_FROM_ORDER_LIST = 'DELETE_FROM_ORDER_LIST';
