export const GET_PRODUCT_LIST_SUCCESS = 'GET_PRODUCT_LIST_SUCCESS';
export const GETTING_PRODUCT_LIST = 'GETTING_PRODUCT_LIST';
export const GET_SHOPCART_DETAIL = 'GET_SHOPCART_DETAIL';
export const ADD_TO_SHOPCART = 'ADD_TO_SHOPCART';
export const UPDATE_AMOUNT_TO_SHOPCART = 'UPDATE_AMOUNT_TO_SHOPCART';
export const DELETE_FROM_SHOPCART = 'DELETE_FROM_SHOPCART';
